#中科大
#[source.crates-io]
#replace-with = 'ustc'

#[source.ustc]
#registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

#[registries.ustc]
#index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# 清华
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.mirror]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"