# Cargo 镜像配置
# 如需更换镜像源，仅需修改此文件，无需修改 Dockerfile

# 清华
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.mirror]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

# 中科大（备选）
#[source.crates-io]
#replace-with = 'ustc'
#
#[source.ustc]
#registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
#
#[registries.ustc]
#index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
