[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-ping",
    "allow-get-device-info",
    "allow-get-network-info",
    "allow-get-battery-info",
    "allow-enter-immersive",
    "allow-exit-immersive",
    "allow-set-status-bar-text-style",
    "allow-set-navigation-bar-button-style",
    "allow-set-status-bar-background-color",
    "allow-set-navigation-bar-background-color",
    "allow-lock-orientation",
    "allow-unlock-orientation",
    "allow-show-toast",
    "allow-move-task-to-back",
    "allow-set-screen-brightness",
    "allow-get-screen-brightness",
    "allow-set-volume",
    "allow-get-volume",
    "allow-pick-folder",
    "allow-share",
    "allow-open-file",
]
